### ISSUE TITLE
should the bnd defaults include `-sources: true`?

### ISSUE THREAD

**Issue by rotty3000** [effectiveosgi/maven-archetypes#2]
wondering if this would be a good idea by default?

**Comment by njbartlett** [comment]
I'm unsure. The conventional maven way seems to be a separate sources (and another separate javadoc) JAR file.

**Comment by rotty3000** [comment]
true... was a fleeting wish, but now it's gone, carry on!

**Comment by njbartlett** [comment]
Oh... well I was happy to have a discussion about it! "I'm unsure" means I'm genuinely unsure and could be persuaded either way.

**Comment by rotty3000** [comment]
It's no trouble! :) The instruction can just as easily be added manually by an enterprising developer. The fact that we're trying to make this (osgi dev/assembly) palatable to the wider maven universe seems reason enough to follow the common practice of having sources and javadoc artifacts built separately.
